### ISSUE TITLE
make prepare出现错误

### ISSUE THREAD

**Issue by fishand73** [TOSPlus/TPS#10]
prepare start
Error: Invalid or corrupt jarfile /home/imxqd/TOS/TPS/build/tools/apktool/apktool.jar
/home/imxqd/TOS/TPS/build/tools/install_framework.sh: 第 19 行: [: -gt: 需要一元表达式
Error: Invalid or corrupt jarfile /home/imxqd/TOS/TPS/build/tools/apktool/apktool.jar
Error: Invalid or corrupt jarfile /home/imxqd/TOS/TPS/build/tools/apktool/apktool.jar
make: **\* [prepare] 错误 1

**Comment by hexiaoshuai** [comment]
在https://github.com/TOSPlus/TPS/blob/master/TPS_user_guide1.11.pdf

4.2  可能时是链接丢失
